name: image_viewer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
  window_size:
      git:
        url: https://github.com/google/flutter-desktop-embedding.git
        path: plugins/window_size
  extended_image: ^6.3.4


dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
      path: ffi
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/empty.jpg

